### ISSUE TITLE
Are you willing to add an open source license?

### ISSUE THREAD

**Issue by hytyotwo** [ibid-11962/Windows-95-3D-Maze-Screensaver#6]
Hi, I'd like to use this as the basis for creating a meme, only replacing the images with my own assets. However, I'm paranoid about being hit with copyright infringement so I was wondering if I could have explicit permission to use this, or have some sort of license applied to this project

**Comment by ibid-11962** [comment]
The matrix libraries used are [from here](https://github.com/esangel/WebGL/tree/master/Common) (MIT license), and the mock desktop is [from here](https://github.com/1j01/98) (unlicensed).

I have no idea about the license of the image assets. I assume most of them are owned by microsoft, but I think some of them are standard opengl test images.

So I can't speak about any of that, but as far as my own code goes you're free to reuse it as you wish. Some attribution would be nice.

**Comment by ck256-2000** [comment]
> Hi, I'd like to use this as the basis for creating a meme, only replacing the images with my own assets. However, I'm paranoid about being hit with copyright infringement so I was wondering if I could have explicit permission to use this, or have some sort of license applied to this project

Hey there hytyotwo - I'm working on something similar - if you'd like to discuss collaboring - lmk - ibid's stuff is pretty cool!!
