### ISSUE TITLE
License and/or permission to use

### ISSUE THREAD

**Issue by chadmandoo** [ibid-11962/Windows-95-3D-Maze-Screensaver#7]
Hello,

I am running a website that is designed to mimic windows 95/98. I ran across your library here.

If I give credit can I use this for the "screensaver" if I can get it working as an overlay?

**Comment by ibid-11962** [comment]
Sure. What's the website?

(Note though that the matrix math libraries are under MIT and the "desktop" part is unlicensed. Both are linked in the readme. I have no idea what the image assets are under. But feel free to use the parts that are my code.)

**Comment by chadmandoo** [comment]
Great! I will certainly credit and link to you.

The website is not up yet but its going to be for my side hustle. Instead of making a generic website I am making it look like you are on windows 95 and interact and learn about my business. I used to love this screen saver so I was hoping to incorporate the screen saver on the website when the user doesnt do anything for X time.

One website that I was inspired by is https://dayjob.work if you want to get an idea of what im trying to go with (they have a screen saver as well)

**Comment by lazerwalker** [comment]
I'm also hoping to use your code for a project! I'm working with folks who are rather finicky about licensing stuff -- is there any chance you'd be willing to add an explicit license, even if it's clear it doesn't apply to the matrix math / desktop / art assets?

Thanks!

**Comment by ibid-11962** [comment]
No plan to do this at the moment.
