### ISSUE TITLE
Question regarding usage of your Project

### ISSUE THREAD

**Issue by 0ort9** [ibid-11962/Windows-95-3D-Maze-Screensaver#9]
Hello, 
we are a Band from Germany and are currently in the process of looking for ideas for a music video. We thought about a video of going through an animated maze like the windows 98 one. We wanted to ask:
-Are you okay with the usage of your project for a music video
-Is there a possibility to change up the textures inside the maze, and the floating objects (to make it less windows like)
We will of course give credit to you for the project if it is possible to use your code :) 
Thank you in advance

**Comment by ck256-2000** [comment]
Hey there - the developer has moved on a bit but does answer from time to time. I worked with him on some mods and came up with what you are suggesting.  you can see examples here: https://linktr.ee/undercurrents_web3  I'd be willing to have a call to discuss this work.  LMK!!

**Comment by 0ort9** [comment]
This is awesome work you put in there!! I am very interested in using this! Could you drop me an E-Mail? s.laudage@outlook.de.

**Comment by ck256-2000** [comment]
Email'ed!

**Comment by ibid-11962** [comment]
@0ort9 I'm okay with you doing pretty much whatever you want with the parts of the code that are mine to give permission to. Look at the other closed issues for the various times I've answered this. Just keep in mind that the matrix library, mock desktop, and image assets aren't mine and so like if this is something important you might want to look into what licenses those have and/or removing them.

A lot of the forks people have made replace the textures with their own. You might want to look there for tips.

**Comment by 0ort9** [comment]
Thank you for the answers!! :)
